"""
Experiment driver: targeted contiguous motif substitutions in WT TP53_e7,
scored with the same PNAS pretuner + AlphaGenome minigene definitions as
``run_hybrid_pnas_alphagenome.py`` / ``run_tp53_double_substitutions.py`` /
``run_tp53_triple_substitutions.py``.

Biological goal
----------------
The single / double / triple exonic-substitution experiments widen the PNAS
pretuner / SR-balance x-axis by accumulating *random* substitutions, but
TP53_e7's AlphaGenome response stays essentially flat across all of them.
This experiment asks a more targeted question: can *deliberately chosen*
motifs push the PNAS x-axis substantially further than random triples do,
and if so, does AlphaGenome finally start to curve?

Two motifs only, for now:

* ``GGA`` -- intended to push PNAS / SR-balance **upward**.
* ``UAG`` (scored in DNA space as ``TAG``, T for U, matching this repo's
  transcript-sense-but-DNA-alphabet convention everywhere else) -- intended
  to push PNAS / SR-balance **downward**.

Each motif is tested as 1x/2x/3x/4x contiguous tandem repeats (lengths 3, 6,
9, 12 nt), and every repeat length is exhaustively slid across every valid
exon start position -- no random sampling. For TP53_e7 (exon length 110):

    length  3 (1x): 110 - 3  + 1 = 108 placements
    length  6 (2x): 110 - 6  + 1 = 105 placements
    length  9 (3x): 110 - 9  + 1 = 102 placements
    length 12 (4x): 110 - 12 + 1 =  99 placements
    per motif total: 108 + 105 + 102 + 99 = 414
    GGA + UAG total: 828 variants, + 1 WT reference row = 829 rows.

Only the exon body is ever touched: each variant is
``exon_seq[:start] + motif*copies + exon_seq[start + len(motif*copies):]``.
The upstream/downstream intronic flanks are always the untouched WT flanks,
so no splice-site flank (inside or outside the exon) besides the exon body
itself is ever modified, and the exon length never changes.

Reuse, not reimplementation
----------------------------
This script does **not** redefine any scoring logic. It reuses, verbatim:

* ``run_hybrid_pnas_alphagenome.load_opensplice_exon`` to build the WT
  ``HybridExon`` for TP53_e7 from ``arush_data/wt_exons.csv``.
* ``run_hybrid_pnas_alphagenome.score_hybrid_variants`` for both PNAS
  (batched) and AlphaGenome (per-record) scoring -- including its built-in
  ``add_deltas`` group-relative-to-reference logic, which just works here
  because (unlike the chunked double/triple scripts) the WT reference row is
  scored in the same batch as every variant, all sharing one
  ``(construct_type, construct_label)`` group.

Only the motif-placement enumeration and CLI plumbing are new.

Duplicate resulting sequences
------------------------------
All 828 placements are enumerated exhaustively (never deduplicated away, so
the row count always matches the counts above), but it is possible in
principle for two different placements to produce byte-identical resulting
exon sequences (e.g. a placement whose target window already reads as the
motif). ``_flag_duplicate_sequences`` checks every resulting ``exon_seq``
(variants + WT) for exact string collisions and records a
``is_duplicate_exon_seq`` column; ``run_score`` prints a report if any are
found. No rows are dropped.

Usage
-----
    python analysis_script/run_tp53_motif_substitutions.py \\
        --alphagenome --env-path .env.alphagenome

Generalized for follow-up experiments (e.g. TP53_e6 4x GGA/UAG, or TP53_e7
UAG pushed out to 15x): ``--exon``, ``--motifs`` (comma-separated subset of
``GGA``/``UAG``) and ``--copy-counts`` (``"4"``, ``"1-15"``, or ``"1,2,4"``)
are all overridable. The defaults (``GGA,UAG`` / ``1-4``) reproduce the
original TP53_e7 1x-4x run exactly, byte-for-byte -- that CSV is not
regenerated by later invocations with different flags, since each run's
output filename is derived from (exon, motifs, copy_counts) and an existing
file is never overwritten without ``--force``. The expected placement count
for any (exon length, motifs, copy_counts) combination is computed in code
by :func:`total_motif_variants` and checked against what was actually
enumerated -- never trusted from a prompt or docstring.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Sequence

_THIS_DIR = Path(__file__).resolve().parent
ROOT = _THIS_DIR.parent
if str(_THIS_DIR) not in sys.path:
    sys.path.insert(0, str(_THIS_DIR))

import pandas as pd  # noqa: E402

import run_hybrid_pnas_alphagenome as hybrid  # noqa: E402

DEFAULT_OPENSPLICE_CSV = hybrid.DEFAULT_OPENSPLICE_CSV
DEFAULT_OUTPUT_DIR = ROOT / "outputs" / "motif_substitutions"

_EXON_CHOICES = ("TP53_e6", "TP53_e7")

#: motif label -> DNA-alphabet repeat unit (U -> T, matching the rest of this
#: repo, which scores exon sequences in DNA space throughout).
MOTIFS: dict[str, str] = {
    "GGA": "GGA",
    "UAG": "TAG",
}
COPY_COUNTS: tuple[int, ...] = (1, 2, 3, 4)

__all__ = [
    "total_motif_variants",
    "build_motif_variant_records",
    "flag_duplicate_sequences",
    "parse_motifs",
    "parse_copy_counts",
    "default_out_name",
]


# ==========================================================================
# Exhaustive motif-placement enumeration
# ==========================================================================

def total_motif_variants(
    exon_length: int,
    motifs: dict[str, str] = MOTIFS,
    copy_counts: Sequence[int] = COPY_COUNTS,
) -> int:
    """Total placements across the given motifs and copy counts.

    Computed independently of any caller's expectations -- this is the
    ground truth ``run_score`` checks the actual enumerated record count
    against, and what the module docstring's worked examples were verified
    against, not the other way around.
    """
    total = 0
    for unit in motifs.values():
        for copies in copy_counts:
            motif_len = len(unit) * copies
            total += max(0, exon_length - motif_len + 1)
    return total


def build_motif_variant_records(
    wt: "hybrid.HybridExon",
    exon_id: str,
    motifs: dict[str, str] = MOTIFS,
    copy_counts: Sequence[int] = COPY_COUNTS,
) -> list[dict[str, Any]]:
    """Materialize one record per (motif, copy_count, start) placement.

    Exhaustive: every valid 0-based ``start`` in
    ``range(0, exon_length - motif_len + 1)`` is enumerated, for every motif x
    copy_count combination. Deterministic ordering: motif (canonical MOTIFS
    order, i.e. GGA before UAG), then copy_count ascending, then start
    ascending.
    """
    base = wt.base_record()
    exon_seq = wt.exon_seq
    n = len(exon_seq)
    records: list[dict[str, Any]] = []

    for motif_name, unit in motifs.items():
        for copies in copy_counts:
            motif_seq = unit * copies
            motif_len = len(motif_seq)
            n_positions = n - motif_len + 1
            if n_positions <= 0:
                continue
            for start in range(n_positions):
                end = start + motif_len
                original_seq = exon_seq[start:end]
                mutated = exon_seq[:start] + motif_seq + exon_seq[end:]
                records.append({
                    **base,
                    "is_reference": False,
                    "mutation_region": "motif_exon",
                    "motif": motif_name,
                    "copy_count": copies,
                    "motif_sequence": motif_seq,
                    "start0": start,
                    "end0": end,
                    "original_seq": original_seq,
                    "exon_seq": mutated,
                })
    return records


def flag_duplicate_sequences(
    records: Sequence[dict[str, Any]],
) -> tuple[list[dict[str, Any]], dict[str, list[str]]]:
    """Mark ``is_duplicate_exon_seq`` on every record whose resulting
    ``exon_seq`` appears more than once among ``records`` (which should
    include the WT reference row, so a placement colliding with WT is
    caught too -- the reference row's own ``exon_seq`` equals the untouched
    WT sequence by construction, so no separate WT check is needed). Nothing
    is dropped -- returns a new list of records plus a
    ``{exon_seq: [placement labels]}`` map of the collisions found, for
    reporting.
    """
    by_seq: dict[str, list[int]] = defaultdict(list)
    for idx, r in enumerate(records):
        by_seq[r["exon_seq"]].append(idx)

    dup_seqs = {seq: idxs for seq, idxs in by_seq.items() if len(idxs) > 1}

    out = [dict(r) for r in records]
    for r in out:
        r["is_duplicate_exon_seq"] = r["exon_seq"] in dup_seqs

    report: dict[str, list[str]] = {}
    for seq, idxs in dup_seqs.items():
        labels = []
        for idx in idxs:
            r = records[idx]
            if r.get("is_reference"):
                labels.append("WT")
            else:
                labels.append(f"{r['motif']}_{r['copy_count']}x@{r['start0']}")
        report[seq] = labels
    return out, report


# ==========================================================================
# CLI arg parsing helpers (--motifs, --copy-counts, derived --out)
# ==========================================================================

def parse_motifs(spec: str) -> dict[str, str]:
    """``"GGA,UAG"`` / ``"UAG"`` -> the matching subset of :data:`MOTIFS`,
    in canonical (GGA-before-UAG) order regardless of the order given."""
    names = [s.strip().upper() for s in spec.split(",") if s.strip()]
    unknown = [nm for nm in names if nm not in MOTIFS]
    if unknown:
        raise ValueError(f"unknown motif(s) {unknown}; choices are {list(MOTIFS)}")
    if not names:
        raise ValueError(f"no motifs parsed from {spec!r}")
    return {nm: unit for nm, unit in MOTIFS.items() if nm in names}


def parse_copy_counts(spec: str) -> tuple[int, ...]:
    """``"1-4"`` -> ``(1,2,3,4)``; ``"4"`` -> ``(4,)``; ``"1,2,4"`` -> ``(1,2,4)``."""
    values: list[int] = []
    for chunk in spec.split(","):
        chunk = chunk.strip()
        if not chunk:
            continue
        if "-" in chunk:
            lo, hi = chunk.split("-", 1)
            values.extend(range(int(lo), int(hi) + 1))
        else:
            values.append(int(chunk))
    if not values:
        raise ValueError(f"no copy counts parsed from {spec!r}")
    return tuple(sorted(set(values)))


def default_out_name(exon_id: str, motifs: dict[str, str], copy_counts: Sequence[int]) -> str:
    """Derive a CSV filename from (exon, motifs, copy_counts) so different
    invocations never collide, and the original defaults reproduce the
    original ``TP53_e7_GGA_UAG_1x_4x.csv`` name exactly."""
    motif_part = "_".join(motifs.keys())
    cc = sorted(copy_counts)
    if len(cc) == 1:
        cc_part = f"{cc[0]}x"
    elif cc == list(range(cc[0], cc[-1] + 1)):
        cc_part = f"{cc[0]}x_{cc[-1]}x"
    else:
        cc_part = "_".join(f"{c}x" for c in cc)
    return f"{exon_id}_{motif_part}_{cc_part}.csv"


# ==========================================================================
# CLI: generate + score in a single pass
# ==========================================================================

OUTPUT_COLUMNS = [
    "exon_id", "is_reference", "mutation_region",
    "motif", "copy_count", "motif_sequence",
    "start0", "end0", "original_seq", "is_duplicate_exon_seq",
    "exon_length", "exon_seq", "upstream_flank", "downstream_flank",
    "pnas_pretuner", "pnas_pretuner_delta",
    "alphagenome_acceptor", "alphagenome_acceptor_delta",
    "alphagenome_donor", "alphagenome_donor_delta",
    "alphagenome_mean_prob", "alphagenome_mean_prob_delta",
    "alphagenome_mean_logit", "alphagenome_mean_logit_delta",
    "alphagenome_prod_logit", "alphagenome_prod_logit_delta",
]


def _order_columns(df: pd.DataFrame) -> pd.DataFrame:
    preferred = [c for c in OUTPUT_COLUMNS if c in df.columns]
    rest = [c for c in df.columns if c not in preferred]
    return df[preferred + rest]


def run_score(args: argparse.Namespace) -> int:
    motifs = parse_motifs(args.motifs)
    copy_counts = parse_copy_counts(args.copy_counts)

    wt = hybrid.load_opensplice_exon(args.exon, args.csv)
    n = wt.exon_length
    expected_total = total_motif_variants(n, motifs=motifs, copy_counts=copy_counts)

    out_dir = args.out_dir if args.out_dir is not None else DEFAULT_OUTPUT_DIR
    out = out_dir / (args.out or default_out_name(args.exon, motifs, copy_counts))
    if out.exists() and not args.force:
        print(f"[skip] {out} already exists (use --force to overwrite)")
        return 0

    dna_model = None
    if args.alphagenome:
        import alphagenome_local_prediction_pipeline_minigene as ag  # noqa: E402

        dna_model = ag.create_model(env_path=args.env_path)

    ref_record = {
        **wt.base_record(),
        "is_reference": True,
        "mutation_region": "reference",
        "motif": None,
        "copy_count": None,
        "motif_sequence": None,
        "start0": None,
        "end0": None,
        "original_seq": None,
    }

    variant_records = build_motif_variant_records(wt, args.exon, motifs=motifs, copy_counts=copy_counts)
    print(
        f"{args.exon}: motifs={list(motifs)} copy_counts={copy_counts} -> "
        f"{len(variant_records)} motif-placement variants "
        f"(independently computed expectation: {expected_total}) + 1 WT reference row"
    )
    if len(variant_records) != expected_total:
        print(
            f"ERROR: generated {len(variant_records)} variants, expected {expected_total}.",
            file=sys.stderr,
        )
        return 1

    all_records, dup_report = flag_duplicate_sequences([ref_record] + variant_records)

    if dup_report:
        print(f"\n[duplicate check] {len(dup_report)} resulting exon_seq value(s) shared by >1 placement:")
        for seq, labels in list(dup_report.items())[:10]:
            print(f"  {labels}")
        if len(dup_report) > 10:
            print(f"  ... and {len(dup_report) - 10} more")
    else:
        print("\n[duplicate check] no duplicate resulting exon sequences found.")

    pnas_kwargs: dict[str, Any] = {"num_threads": args.pnas_threads}
    if args.device:
        pnas_kwargs["device"] = args.device

    df = hybrid.score_hybrid_variants(
        all_records, dna_model,
        run_pnas=True, run_alphagenome=args.alphagenome,
        add_deltas=True, pnas_kwargs=pnas_kwargs,
    )
    df.insert(0, "exon_id", args.exon)
    df = _order_columns(df)

    out_dir.mkdir(parents=True, exist_ok=True)
    df.to_csv(out, index=False)
    print(f"\nwrote {len(df)} rows -> {out}")
    return 0


# ==========================================================================
# CLI
# ==========================================================================

def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Exhaustive GGA / UAG tandem-motif exonic substitution scoring for TP53_e7."
    )
    parser.add_argument("--exon", default="TP53_e7", choices=_EXON_CHOICES)
    parser.add_argument("--csv", type=Path, default=DEFAULT_OPENSPLICE_CSV)
    parser.add_argument("--motifs", default="GGA,UAG",
                        help="comma-separated subset of {GGA,UAG} (default: GGA,UAG)")
    parser.add_argument("--copy-counts", default="1-4",
                        help="copy counts to test, e.g. '1-4', '4', or '1,2,4' (default: 1-4)")
    parser.add_argument("--alphagenome", action="store_true",
                        help="also run AlphaGenome (needs an API key via --env-path)")
    parser.add_argument("--env-path", default=".env.alphagenome")
    parser.add_argument("--device", default=None, help="PNAS torch device override")
    parser.add_argument("--pnas-threads", type=int, default=8)
    parser.add_argument("--out-dir", type=Path, default=None,
                        help="output directory (default outputs/motif_substitutions/)")
    parser.add_argument("--out", default=None,
                        help="output filename (default derived from exon/motifs/copy-counts)")
    parser.add_argument("--force", action="store_true",
                        help="overwrite an existing output file")
    args = parser.parse_args(argv)

    return run_score(args)


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
